import PDFDocument from 'pdfkit'

const PINK = '#e94480'
const PINK_LIGHT = '#fce4ec'
const TEXT_DARK = '#1a1a1a'
const TEXT_SEC = '#555555'
const TEXT_TER = '#888888'

const CONSENT_STATEMENT = 'I confirm that the information I have provided is accurate and complete. I consent to the tooth jewellery procedure being carried out and agree to follow all aftercare instructions. I understand that the procedure involves the application of a Swarovski or Preciosa crystal to my tooth using dental adhesive, and I am aware of the risks and aftercare requirements as explained to me by Ethereal Smile.'

const GUARDIAN_STATEMENT = 'I, the parent or legal guardian of the above-named young person, hereby give my consent for the tooth jewellery procedure to be carried out. I confirm that the medical information provided is accurate to the best of my knowledge. I understand the procedure and aftercare requirements and accept responsibility for ensuring they are followed.'

const AFTERCARE_STATEMENT = 'I have read and understood the aftercare information provided. I will follow all aftercare instructions as explained by Ethereal Smile.'

const MEDICAL_LABELS = {
  abscessOrUlcer: 'Abscess or ulcer',
  ongoingDentalProblems: 'Ongoing dental problems',
  falseToothOrVeneers: 'False tooth or veneers',
  pregnantOrBreastfeeding: 'Pregnant or breastfeeding',
  invisalignOrRetainer: 'Invisalign or retainer',
  halitosis: 'Halitosis (bad breath)',
  oralHerpes: 'Oral herpes / cold sores',
  recentDentalSurgery: 'Recent dental surgery',
  sensitiveTeeth: 'Sensitive teeth',
}

function drawHeader(doc, title) {
  // Pink top bar
  doc.rect(0, 0, doc.page.width, 60).fill(PINK)

  // Title text
  doc.fontSize(18).font('Helvetica-Bold')
    .fillColor('#ffffff')
    .text(title, 50, 18, { width: doc.page.width - 100 })

  // Reset cursor below header
  doc.fillColor(TEXT_DARK)
  doc.y = 80
}

function drawSectionTitle(doc, title) {
  doc.moveDown(0.5)
  doc.fontSize(11).font('Helvetica-Bold').fillColor(PINK).text(title.toUpperCase())
  doc.moveDown(0.3)
  doc.strokeColor('#e0e0e0').lineWidth(0.5)
    .moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke()
  doc.moveDown(0.5)
  doc.fillColor(TEXT_DARK)
}

function drawField(doc, label, value, opts = {}) {
  const startY = doc.y
  doc.fontSize(8).font('Helvetica').fillColor(TEXT_TER).text(label.toUpperCase(), 50, doc.y, { width: opts.twoCol ? 220 : doc.page.width - 100 })
  const labelHeight = doc.y - startY
  doc.fontSize(10).font('Helvetica').fillColor(TEXT_DARK).text(value || 'Not provided', 50, doc.y + 2, { width: opts.twoCol ? 220 : doc.page.width - 100 })
  doc.moveDown(0.3)
}

function drawCheckbox(doc, label, checked) {
  const y = doc.y
  doc.fontSize(10).font('Helvetica').fillColor(TEXT_DARK)

  // Draw checkbox square
  doc.rect(50, y + 1, 10, 10).lineWidth(0.5).strokeColor('#cccccc').stroke()
  if (checked) {
    doc.fontSize(10).fillColor(PINK).text('\u2713', 51.5, y + 0.5)
  }

  doc.fillColor(TEXT_DARK).text(label, 66, y + 1, { width: doc.page.width - 116 })
  doc.moveDown(0.1)
}

function drawStatement(doc, text) {
  const startY = doc.y
  doc.rect(50, startY, doc.page.width - 100, 2).fill(PINK)
  doc.moveDown(0.5)

  doc.fontSize(9).font('Helvetica-Oblique').fillColor(TEXT_DARK)
    .text(text, 50, doc.y, { width: doc.page.width - 100, lineGap: 3 })
  doc.moveDown(0.5)
}

function drawSignatureBlock(doc, signatoryName, signedAt, ip) {
  doc.moveDown(0.5)

  // Signature line
  doc.strokeColor(TEXT_DARK).lineWidth(0.5)
    .moveTo(50, doc.y + 20).lineTo(250, doc.y + 20).stroke()

  doc.fontSize(8).font('Helvetica').fillColor(TEXT_TER)
    .text('SIGNATURE (typed)', 50, doc.y + 24)

  doc.fontSize(12).font('Helvetica-Bold').fillColor(TEXT_DARK)
    .text(signatoryName, 50, doc.y - 18)

  doc.moveDown(1)

  // Date and IP
  doc.fontSize(8).font('Helvetica').fillColor(TEXT_TER)
  doc.text('Date: ' + (signedAt ? new Date(signedAt).toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'long' }) : 'Not signed'), 50, doc.y, { continued: false })
  doc.text('IP Address: ' + (ip || 'Not recorded'), 50, doc.y, { width: doc.page.width - 100 })
}

function drawFooter(doc, documentType, documentVersion, originalPdfUrl) {
  doc.moveDown(1)
  doc.strokeColor('#e0e0e0').lineWidth(0.5)
    .moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke()
  doc.moveDown(0.5)

  doc.fontSize(7).font('Helvetica').fillColor(TEXT_TER)
    .text('This is the completed consent record generated by Ethereal Smile.', 50, doc.y, { width: doc.page.width - 100 })
  doc.text('Consented to: ' + documentType + ' (version ' + (documentVersion || '1.0') + ')', 50, doc.y, { width: doc.page.width - 100 })
  doc.text('Original document: ' + (originalPdfUrl || 'N/A'), 50, doc.y, { width: doc.page.width - 100 })
  doc.text('This record is immutable and cannot be modified after signing.', 50, doc.y, { width: doc.page.width - 100 })

  doc.moveDown(1)
  doc.fontSize(7).font('Helvetica').fillColor(TEXT_TER)
    .text('Ethereal Smile by Hattie Clifford | etherealsmile.co.uk', 50, doc.y, { width: doc.page.width - 100, align: 'center' })
}

export function generateConsentPdf({ documentType, documentTitle, documentVersion, pdfUrl, responses, signatoryName, signatoryRelationship, signedAt, signedIp, clientName, clientEmail }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 20, bottom: 40, left: 50, right: 50 },
        info: {
          Title: documentTitle + ' - Consent Record',
          Author: 'Ethereal Smile',
          Subject: 'Completed consent form for ' + (clientName || 'client'),
          Creator: 'Ethereal Smile Consent System',
        }
      })

      const chunks = []
      doc.on('data', (chunk) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))

      // Page 1: Header
      drawHeader(doc, documentTitle + ' - Consent Record')

      // Subtitle
      doc.fontSize(10).font('Helvetica').fillColor(TEXT_SEC)
        .text('Ethereal Smile by Hattie Clifford', 50, doc.y, { width: doc.page.width - 100, align: 'center' })
      doc.moveDown(0.5)

      // Client info
      drawSectionTitle(doc, 'Client Information')
      drawField(doc, 'Client Name', clientName || 'Not provided')
      drawField(doc, 'Email', clientEmail || 'Not provided')

      // Document info
      drawField(doc, 'Document Type', documentType)
      drawField(doc, 'Document Version', documentVersion || '1.0')
      drawField(doc, 'Date Signed', signedAt ? new Date(signedAt).toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'long' }) : 'N/A')

      // Type-specific content
      if (documentType === 'consent' || documentType === 'consultation') {
        // Personal details
        drawSectionTitle(doc, 'Personal Details')
        drawField(doc, 'Full Name', responses.fullName)
        drawField(doc, 'Date of Birth', responses.dateOfBirth)
        drawField(doc, 'Age', responses.age)
        drawField(doc, 'Phone', responses.phone)
        drawField(doc, 'Email', responses.email)
        drawField(doc, 'Address', responses.address)

        // Medical history
        drawSectionTitle(doc, 'Medical History')
        drawField(doc, 'Allergies', responses.allergies || 'None stated')

        const conditions = responses.medicalConditions || {}
        Object.keys(MEDICAL_LABELS).forEach((key) => {
          drawCheckbox(doc, MEDICAL_LABELS[key], !!conditions[key])
        })

        drawCheckbox(doc, 'Vomiting, diarrhoea, or infection in last 48 hours', !!responses.illnessInLast48h)

        // Consent statement
        drawSectionTitle(doc, 'Declaration & Consent')
        drawStatement(doc, CONSENT_STATEMENT)
        drawCheckbox(doc, 'Consent statement agreed', !!responses.consentAgreed)

      } else if (documentType === 'guardian_consent') {
        // Young person details
        drawSectionTitle(doc, "Young Person's Details")
        drawField(doc, "Young Person's Name", responses.youngPersonName)
        drawField(doc, "Young Person's Date of Birth", responses.youngPersonDOB)

        // Guardian details
        drawSectionTitle(doc, "Guardian's Details")
        drawField(doc, "Guardian's Name", responses.guardianName)
        drawField(doc, 'Relationship', responses.guardianRelationship)
        drawField(doc, 'Address', responses.guardianAddress)
        drawField(doc, 'Postcode', responses.guardianPostcode)
        drawField(doc, 'Contact Number', responses.guardianPhone)

        // Guardian consent statement
        drawSectionTitle(doc, 'Guardian Consent Statement')
        drawStatement(doc, GUARDIAN_STATEMENT)
        drawCheckbox(doc, 'Guardian consent statement agreed', !!responses.consentStatementAgreed)

      } else if (documentType === 'aftercare') {
        drawSectionTitle(doc, 'Aftercare Acknowledgment')
        drawStatement(doc, AFTERCARE_STATEMENT)
        drawCheckbox(doc, 'Aftercare information read and understood', !!responses.readAcknowledged)
      }

      // Signature
      drawSectionTitle(doc, 'Electronic Signature')
      drawSignatureBlock(doc, signatoryName, signedAt, signedIp)

      if (signatoryRelationship && signatoryRelationship !== 'self') {
        doc.fontSize(8).font('Helvetica').fillColor(TEXT_TER)
          .text('Signed as: ' + signatoryRelationship, 50, doc.y)
      }

      // Footer
      drawFooter(doc, documentType, documentVersion, pdfUrl)

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}