import { jsPDF } from 'jspdf'

const PINK = '#e94480'
const PINK_LIGHT = '#fce4ec'
const TEXT_DARK = '#1a1a1a'
const TEXT_SEC = '#555555'
const TEXT_TER = '#888888'
const DIVIDER = '#e0e0e0'

const CONSENT_STATEMENT = 'I confirm that the information I have provided is accurate and complete. I consent to the tooth jewellery procedure being carried out and agree to follow all aftercare instructions. I understand that the procedure involves the application of a Swarovski or Preciosa crystal to my tooth using dental adhesive, and I am aware of the risks and aftercare requirements as explained to me by Ethereal Smile.'

const GUARDIAN_STATEMENT = 'I, the parent or legal guardian of the above-named young person, hereby give my consent for the tooth jewellery procedure to be carried out. I confirm that the medical information provided is accurate to the best of my knowledge. I understand the procedure and aftercare requirements and accept responsibility for ensuring they are followed.'

const AFTERCARE_STATEMENT = 'I have read and understood the aftercare information provided. I will follow all aftercare instructions as explained by Ethereal Smile.'

const MEDICAL_LABELS = {
  abscessOrUlcer: 'Abscess or ulcer',
  ongoingDentalProblems: 'Ongoing dental problems',
  falseToothOrVeneers: 'False tooth or veneers',
  pregnantOrBreastfeeding: 'Pregnant or breastfeeding',
  invisalignOrRetainer: 'Invisalign or retainer',
  halitosis: 'Halitosis (bad breath)',
  oralHerpes: 'Oral herpes / cold sores',
  recentDentalSurgery: 'Recent dental surgery',
  sensitiveTeeth: 'Sensitive teeth',
}

export function generateConsentPdf({ documentType, documentTitle, documentVersion, pdfUrl, responses, signatoryName, signatoryRelationship, signedAt, signedIp, clientName, clientEmail }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = margin

  function addHeader(title) {
    doc.setFillColor(233, 68, 128)
    doc.rect(0, 0, pageWidth, 22, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin, 14)
    doc.setTextColor(TEXT_DARK)
    y = 30
  }

  function addSectionTitle(title) {
    y += 4
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(233, 68, 128)
    doc.text(title.toUpperCase(), margin, y)
    y += 1
    doc.setDrawColor(224, 224, 224)
    doc.line(margin, y, pageWidth - margin, y)
    y += 4
    doc.setTextColor(TEXT_DARK)
  }

  function addField(label, value) {
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(TEXT_TER)
    doc.text(label.toUpperCase(), margin, y)
    y += 3.5
    doc.setFontSize(9)
    doc.setTextColor(TEXT_DARK)
    const safeValue = (value || 'Not provided').replace(/[()]/g, function(m) { return '\\' + m })
    const lines = doc.splitTextToSize(safeValue, contentWidth)
    doc.text(lines, margin, y)
    y += Math.max(lines.length * 4.5, 5)
  }

  function addCheckbox(label, checked) {
    const boxX = margin
    const boxY = y - 2.5
    doc.setDrawColor(180, 180, 180)
    doc.setLineWidth(0.3)
    doc.rect(boxX, boxY, 3.5, 3.5)
    if (checked) {
      doc.setFontSize(10)
      doc.setTextColor(233, 68, 128)
      doc.text('\u2713', boxX + 0.5, boxY + 3)
    }
    doc.setFontSize(8.5)
    doc.setTextColor(TEXT_DARK)
    const safeLabel = label.replace(/[()]/g, function(m) { return '\\' + m })
    doc.text(safeLabel, margin + 5.5, y + 0.5)
    y += 5
  }

  function addStatement(text) {
    y += 2
    doc.setFillColor(233, 68, 128)
    doc.rect(margin, y, contentWidth, 0.8, 'F')
    y += 4
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(TEXT_DARK)
    const lines = doc.splitTextToSize(text, contentWidth)
    doc.text(lines, margin, y)
    y += lines.length * 4.5 + 2
  }

  function addSignatureBlock(name, dateStr, ip) {
    y += 4
    doc.setDrawColor(TEXT_DARK)
    doc.setLineWidth(0.3)
    doc.line(margin, y + 8, margin + 70, y + 8)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(TEXT_DARK)
    doc.text(name, margin, y + 6)
    y += 12
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(TEXT_TER)
    doc.text('Date: ' + dateStr, margin, y)
    doc.text('IP: ' + (ip || 'Not recorded'), margin + 80, y)
    y += 5
  }

  function addFooter(docType, docVersion, originalUrl) {
    const pageHeight = doc.internal.pageSize.getHeight()
    y = pageHeight - 20
    doc.setDrawColor(224, 224, 224)
    doc.line(margin, y - 5, pageWidth - margin, y - 5)
    doc.setFontSize(6.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(TEXT_TER)
    doc.text('This is the completed consent record generated by Ethereal Smile.', margin, y)
    doc.text('Consented to: ' + docType + ' (version ' + (docVersion || '1.0') + ')', margin, y + 3.5)
    doc.text('Original document: ' + (originalUrl || 'N/A'), margin, y + 7)
    doc.text('This record is immutable and cannot be modified after signing.', margin, y + 10.5)
    doc.setFontSize(6)
    doc.text('Ethereal Smile by Hattie Clifford | etherealsmile.co.uk', margin, y + 15)
  }

  function checkPage(needed) {
    if (y + needed > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage()
      y = margin
    }
  }

  // Build the PDF
  addHeader(documentTitle + ' - Consent Record')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(TEXT_SEC)
  doc.text('Ethereal Smile by Hattie Clifford', pageWidth / 2, y, { align: 'center' })
  y += 6

  addSectionTitle('Client Information')
  addField('Client Name', clientName)
  addField('Email', clientEmail)
  addField('Document Type', documentType)
  addField('Document Version', documentVersion || '1.0')
  addField('Date Signed', signedAt ? new Date(signedAt).toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'long' }) : 'N/A')

  if (documentType === 'consent' || documentType === 'consultation') {
    checkPage(80)
    addSectionTitle('Personal Details')
    addField('Full Name', responses.fullName)
    addField('Date of Birth', responses.dateOfBirth)
    addField('Age', responses.age)
    addField('Phone', responses.phone)
    addField('Email', responses.email)
    addField('Address', responses.address)

    checkPage(60)
    addSectionTitle('Medical History')
    addField('Allergies', responses.allergies || 'None stated')
    addField('Current Medications', responses.currentMedications || 'None stated')

    const conditions = responses.medicalConditions || {}
    Object.keys(MEDICAL_LABELS).forEach(function(key) {
      checkPage(6)
      addCheckbox(MEDICAL_LABELS[key], !!conditions[key])
    })
    checkPage(6)
    addCheckbox('Vomiting, diarrhoea, or infection in last 48 hours', !!responses.illnessInLast48h)

    addField('Dental Issues', responses.dentalIssues || 'None stated')
    addField('Previous Tooth Gems', responses.previousToothGems || 'None')

    checkPage(30)
    addSectionTitle('Declaration & Consent')
    addStatement(CONSENT_STATEMENT)
    checkPage(6)
    addCheckbox('Consent statement agreed', !!responses.consentAgreed)

  } else if (documentType === 'guardian_consent') {
    checkPage(40)
    addSectionTitle("Young Person's Details")
    addField("Young Person's Name", responses.youngPersonName)
    addField("Young Person's Date of Birth", responses.youngPersonDOB)

    addSectionTitle("Guardian's Details")
    addField("Guardian's Name", responses.guardianName)
    addField('Relationship', responses.guardianRelationship)
    addField('Address', responses.guardianAddress)
    addField('Postcode', responses.guardianPostcode)
    addField('Contact Number', responses.guardianPhone)

    checkPage(30)
    addSectionTitle('Guardian Consent Statement')
    addStatement(GUARDIAN_STATEMENT)
    checkPage(6)
    addCheckbox('Guardian consent agreed', !!responses.consentStatementAgreed)

  } else if (documentType === 'aftercare') {
    addSectionTitle('Aftercare Acknowledgment')
    addStatement(AFTERCARE_STATEMENT)
    addCheckbox('Aftercare information read and understood', !!responses.readAcknowledged)
  }

  checkPage(30)
  addSectionTitle('Electronic Signature')
  addSignatureBlock(signatoryName, signedAt ? new Date(signedAt).toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'long' }) : 'N/A', signedIp)

  if (signatoryRelationship && signatoryRelationship !== 'self') {
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(TEXT_TER)
    doc.text('Signed as: ' + signatoryRelationship, margin, y)
  }

  addFooter(documentType, documentVersion, pdfUrl)

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'))
  return pdfBuffer
}
